-- MySQL Script generated by MySQL Workbench
-- Wed Feb 27 18:38:18 2019
-- Model: New Model    Version: 10
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table Category
-- -----------------------------------------------------
CREATE TABLE Category(
  Category_ID INT NOT NULL,
  category_name VARCHAR(45) NOT NULL,
  PRIMARY KEY (Category_ID));


-- -----------------------------------------------------
-- Table Customer
-- -----------------------------------------------------
CREATE TABLE Customer (
  Customer_ID INT NOT NULL,
  Last_name VARCHAR(45) NOT NULL,
  First_name VARCHAR(45) NOT NULL,
  Street VARCHAR(45) NOT NULL,
  addressLine_1 VARCHAR(45) NOT NULL,
  addressLine_2 VARCHAR(45) NULL,
  City VARCHAR(45) NOT NULL,
  State VARCHAR(45) NULL,
  Country VARCHAR(45) NOT NULL,
  ZipCode VARCHAR(45) NOT NULL,
  Email VARCHAR(45) NULL,
  Phone_number VARCHAR(12) NULL,
  Confirmation_Code VARCHAR(45) NULL,
  Payment_Method VARCHAR(45) NULL,
  PRIMARY KEY (Customer_ID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Stores
-- -----------------------------------------------------
CREATE TABLE Stores (
  Store_ID INT NOT NULL,
  Street VARCHAR(45) NULL,
  addressLine1 VARCHAR(45) NULL,
  addressLine2 VARCHAR(45) NULL,
  City VARCHAR(45) NULL,
  State VARCHAR(45) NULL,
  Country VARCHAR(45) NULL,
  ZipCode VARCHAR(45) NULL,
  Email VARCHAR(45) NULL,
  PhoneNumber VARCHAR(12) NULL,
  PRIMARY KEY (Store_ID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Employee
-- -----------------------------------------------------
CREATE TABLE Employee (
  Employee_ID INT NOT NULL,
  First_name VARCHAR(45) NULL,
  Last_name VARCHAR(45) NULL,
  phoneNumber VARCHAR(12) NULL,
  Car_Model VARCHAR(45) NULL,
  Store_ID INT NOT NULL,
  PRIMARY KEY (Employee_ID),
  INDEX fk_Employee_Stores1_idx (Store_ID ASC) VISIBLE,
  CONSTRAINT fk_Employee_Stores1
    FOREIGN KEY (Store_ID)
    REFERENCES Stores (Store_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Orders
-- -----------------------------------------------------
CREATE TABLE Orders (
  Order_ID INT NOT NULL,
  Ordered_On DATETIME NOT NULL,
  Customer_ID INT NOT NULL,
  estimated_delivery_Time DATETIME NULL,
  actual_delivery_Time TIMESTAMP(5) NULL,
  status VARCHAR(45) NULL,
  Delivered_By INT NULL,
  PRIMARY KEY (Order_ID),
  INDEX fk_Order_Customer1_idx (Customer_ID ASC) VISIBLE,
  INDEX fk_Orders_Employee1_idx (Delivered_By ASC) VISIBLE,
  CONSTRAINT fk_Order_Customer1
    FOREIGN KEY (Customer_ID)
    REFERENCES Customer (Customer_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Orders_Employee1
    FOREIGN KEY (Delivered_By)
    REFERENCES Employee (Employee_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Items
-- -----------------------------------------------------
CREATE TABLE Items (
  Item_ID INT NOT NULL,
  item_name VARCHAR(45) NOT NULL,
  description VARCHAR(45) NOT NULL,
  price DECIMAL(6,2) NOT NULL,
  Category_ID INT NOT NULL,
  Order_ID INT NULL,
  Store_ID INT NOT NULL,
  PRIMARY KEY (Item_ID),
  INDEX fk_Items_Category1_idx (Category_ID ASC) VISIBLE,
  INDEX fk_Items_Orders1_idx (Order_ID ASC) VISIBLE,
  INDEX fk_Items_Stores1_idx (Store_ID ASC) VISIBLE,
  CONSTRAINT fk_Items_Category1
    FOREIGN KEY (Category_ID)
    REFERENCES Category (Category_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Items_Orders1
    FOREIGN KEY (Order_ID)
    REFERENCES Orders (Order_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Items_Stores1
    FOREIGN KEY (Store_ID)
    REFERENCES Stores (Store_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Promotions
-- -----------------------------------------------------
CREATE TABLE Promotions (
  Promotion_ID INT NOT NULL,
  discount DECIMAL(6,2) NULL,
  time_duration TIME NULL,
  PromoCode VARCHAR(45) NULL,
  Item_ID INT NULL,
  Customer_ID INT NULL,
  PRIMARY KEY (Promotion_ID),
  INDEX fk_Promotions_Items1_idx (Item_ID ASC) VISIBLE,
  INDEX fk_Promotions_Customer1_idx (Customer_ID ASC) VISIBLE,
  CONSTRAINT fk_Promotions_Items1
    FOREIGN KEY (Item_ID)
    REFERENCES Items (Item_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Promotions_Customer1
    FOREIGN KEY (Customer_ID)
    REFERENCES Customer (Customer_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Rating
-- -----------------------------------------------------
CREATE TABLE Rating (
  Rating_ID INT NOT NULL,
  Rating INT(5) NULL,
  Employee_Rated INT NULL,
  Rated_By INT NULL,
  PRIMARY KEY (Rating_ID),
  INDEX fk_Rating_Employee1_idx (Employee_Rated ASC) VISIBLE,
  INDEX fk_Rating_Customer1_idx (Rated_By ASC) VISIBLE,
  CONSTRAINT fk_Rating_Employee1
    FOREIGN KEY (Employee_Rated)
    REFERENCES Employee (Employee_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Rating_Customer1
    FOREIGN KEY (Rated_By)
    REFERENCES Customer (Customer_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Favorites
-- -----------------------------------------------------
CREATE TABLE Favorites (
  Favorites_ID INT NOT NULL,
  Item_ID INT NULL,
  Customer_ID INT NOT NULL,
  PRIMARY KEY (Favorites_ID),
  INDEX fk_Favorites_Items1_idx (Item_ID ASC) VISIBLE,
  INDEX fk_Favorites_Customer1_idx (Customer_ID ASC) VISIBLE,
  CONSTRAINT fk_Favorites_Items1
    FOREIGN KEY (Item_ID)
    REFERENCES Items (Item_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Favorites_Customer1
    FOREIGN KEY (Customer_ID)
    REFERENCES Customer (Customer_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
